name: Test with ESLint, Typescript & Build app
on:
  push:
jobs:
  test_n_build:
    name: ⬣, 🔎, ⚡, 🔨 Lint, Typecheck, and Build app
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
    strategy:
      matrix:
        node-version: [16.x]
        pnpm-version: [7.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: ⬣ ESLint
        run: pnpm lint
      - name: 🔎 Typecheck
        run: pnpm typecheck
      - name: 🔨 Build app
        run: pnpm build
